### PR TITLE
Update ru

### PR DESCRIPTION
**Pull request by andrey-helldar**
* Added new words
* Added new word variations
* Removed not bad words
* Sorted alphabetically

### CODE REVIEW

**Comment by ConsoleTVs** [comment]
Please run `build.py` to create the output file with the new words.

**Comment by andrey-helldar** [comment]
Unfortunately, I don't have python installed.

**Comment by andrey-helldar** [comment]
I updated the `output.json` file.

Hm...
image

**Comment by andrey-helldar** [comment]
- "Петух" - used as an insult during abusive conversation, but "петух" is a male chicken.
- "Сука" - used as an insult during abusive conversation, it is used as an insult. In English, this word is translated as "bitch". But "сука" (suka) in Russian means a female dog.

**Pull request merged**
